name: "Deploy to Github Pages"
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn deploy-storybook --ci --host-token-env-variable=SB_DEPLOY_GH_TOKEN
